default:
  interruptible: true
  image: docker:latest
  services:
    - docker:dind
  timeout: 1h 30m

stages:
  - build
  - build_fail
  - test
  - deploy
  - dast

lint-Dockerfile:
  stage: build
  script:
    - docker pull hadolint/hadolint
    - docker run --rm -i hadolint/hadolint < Dockerfile
  allow_failure: true
  only:
    - master

lint-swarm-Dockerfile:
  stage: build
  script:
    - docker pull hadolint/hadolint
    - docker run --rm -i hadolint/hadolint < ./manager/swarm.Dockerfile
  only:
    - master

build-master:
  stage: build
  before_script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - mkdir -p /root/.docker/cli-plugins
    - mv .docker/cli-plugins/docker-buildx /root/.docker/cli-plugins/
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker buildx use default
    - docker buildx ls
    - docker context ls
    - docker buildx build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker run -v $(pwd):/or "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "./gradlew --console plain clean installDist"
    - docker run -v $(pwd):/or
      -v /var/run/docker.sock:/var/run/docker.sock
      "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/deploy.yml build --build-arg GIT_COMMIT=$SOURCE_COMMIT"
    - docker push openremote/deployment:${CACHE_TAG:-latest}
    - docker push openremote/manager:${CACHE_TAG:-latest}
    - docker push openremote/manager-swarm:${CACHE_TAG:-latest}
    ## TODO dind does not support arm64 archieture for now, therefore the code below breaks the build
    # # Build ARM images
    # - docker buildx build --platform linux/arm64 -t openremote/manager:arm64 manager/build/install/manager
    # - docker buildx build --platform linux/arm64 -t openremote/deployment:arm64 deployment
    # - docker buildx build --platform linux/arm64 -t openremote/proxy:arm64 proxy
    # - docker buildx build --platform linux/arm64 -t openremote/keycloak:arm64 keycloak
    # - docker buildx build --platform linux/arm64 -t openremote/postgresql:arm64 postgresql
    # # Push ARM images
    # - docker push openremote/manager:arm64
    # - docker push openremote/deployment:arm64
    # - docker push openremote/proxy:arm64
    # - docker push openremote/keycloak:arm64
    # - docker push openremote/postgresql:arm64
  only:
    - master

# This step is executed when build fails. The purpose is to e-mail a git commiter about the problem.
email failed pipeline:
  stage: build_fail
  image: docker:latest
  script:
    - docker pull registry.gitlab.com/openremote/openremote:master
    - export WHO=$(docker run --rm -v $(pwd):/or registry.gitlab.com/openremote/openremote:master git log --pretty="%ce" -1)
    - export WHEN=$(docker run --rm -v $(pwd):/or registry.gitlab.com/openremote/openremote:master git log --pretty="%ad %ar" -1)
    - export WHAT=$(docker run --rm -v $(pwd):/or registry.gitlab.com/openremote/openremote:master git log --pretty="%h %s" -1)
    - export REPO=$(docker run --rm -v $(pwd):/or registry.gitlab.com/openremote/openremote:master git remote get-url origin|xargs basename)
    - echo $REPO
    - docker run -v $(pwd):/usr/src/myapp -w /usr/src/myapp
      -e "WHO=$WHO"
      -e "WHAT=$WHAT"
      -e "WHEN=$WHEN"
      -e "REPO=$REPO"
      -e "SMTP_USERNAME=$SMTP_USERNAME"
      -e "SMTP_PASSWORD=$SMTP_PASSWORD"
      --rm python:3 python deployment/aws-mail.py
  when: on_failure
  only:
    - master

test-master:
  before_script:
    - docker run -v $(pwd):/or
      -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/dev-testing.yml pull"
    - docker run -v $(pwd):/or
      -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/dev-testing.yml up --no-build -d"
  script:
    - docker run --network host -v $(pwd):/or "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "./gradlew clean build installDist"
  # Still has 3 errors, therefore allow it to fail
  allow_failure: true
  only:
    - master

deploy-master:
  stage: deploy
  script:
    - echo Continous deploy TODO
  only:
    - master