default:
  interruptible: true
  image: docker:latest
  services:
    - docker:dind
  timeout: 1h 30m

lint-Dockerfile:
  stage: build
  script:
    - docker pull hadolint/hadolint
    - docker run --rm -i hadolint/hadolint < Dockerfile
  allow_failure: true

lint-swarm-Dockerfile:
  stage: build
  script:
    - docker pull hadolint/hadolint
    - docker run --rm -i hadolint/hadolint < ./manager/swarm.Dockerfile

build-master:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker run -v $(pwd):/openremote "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "./gradlew --console plain clean installDist"
    - docker run -v $(pwd):/openremote
      -v /var/run/docker.sock:/var/run/docker.sock
      "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/deploy.yml build --build-arg GIT_COMMIT=$SOURCE_COMMIT"
    - docker push openremote/deployment:${CACHE_TAG:-latest}
    - docker push openremote/manager:${CACHE_TAG:-latest}
    - docker push openremote/manager-swarm:${CACHE_TAG:-latest}
  only:
    - master

test-master:
  before_script:
    - docker run -v $(pwd):/openremote
      -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/dev-testing.yml pull"
    - docker run -v $(pwd):/openremote
      -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "docker-compose -f profile/dev-testing.yml up --no-build -d"
  script:
    - docker run --network host -v $(pwd):/openremote "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      /bin/sh -c "./gradlew clean build installDist"
  # Still has 3 errors, therefore allow it to fail
  allow_failure: true
  only:
    - master

deploy-master:
  stage: deploy
  script:
    - echo Continous deploy TODO
  only:
    - master