version: '2'
services:

  # This is the API gateway for the whole system and hosting the public resources
  # of the manager web application.
  manager:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/manager:latest

    # This application exposes a public web service that should be mapped to a host
    # port. The default is '8080', this is the port on your Docker host to access
    # the application. The second '8080' must match the service-internal port (see below).
    ports:
      - "8080:8080"

    # This service needs access to other services on the Docker network.
    depends_on:
      - orion
      - keycloak

    environment:

      # It is important that all services have the same timezone and are time synchronized.
      # Bearer tokens are only valid for minutes, and authentication fails if Keycloak drifts.
      TZ: "Europe/Zurich"

      # If dev mode is enabled, caching and other performance-optimizations will be disabled.
      DEV_MODE: 'false'

      # If this is the first time you are starting this stack, and/or with non-persistent
      # context broker (the default), you might want to work with some automatically imported
      # sample data.
      IMPORT_SAMPLE_DATA: 'true'

      # The service-internal interface and port to listen on. This should not be changed.
      WEBSERVER_LISTEN_HOST: 0.0.0.0
      WEBSERVER_LISTEN_PORT: 8080

      # The public host name of this OpenRemote installation. This name is used in bearer tokens
      # and must be the name you access the web services under. If you are using Docker Toolbox,
      # this is the IP of a virtual machine running the Linux Docker host (see VirtualBox).
      IDENTITY_NETWORK_HOST: '192.168.99.100'

      # The public port of this OpenRemote installation. For simple installations without an
      # HTTP proxy in front of this application, this will be the public webservice host-mapped
      # port.
      IDENTITY_NETWORK_WEBSERVER_PORT: 8080

      # The service-internal host name and port of the context broker, configured automatically.
      CONTEXTBROKER_HOST: orion
      CONTEXTBROKER_PORT: 1026

      # The service-internal host name and port of the identity provider, configured automatically.
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

  # The identity provider, we use OAuth2 and bearer tokens for all API access.
  keycloak:
    image: openremote/keycloak:latest
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: admin

      # Change the admin root passwort if you make this application publicly accessible! Note
      # that imported sample data also creates a 'test' user with password 'test'. This should
      # not be imported in production.
      KEYCLOAK_PASSWORD: admin

  # MongoDB is the storage backend of Orion.
  mongo:
    image: mongo:2.6
    command: --smallfiles
    environment:
        TZ: "Europe/Zurich"

  # Orion is the context broker, it holds the current state of all IoT assets and devices.
  orion:
    image: fiware/orion:0.28
    links:
      - mongo
    command: -dbhost mongo
    environment:
        TZ: "Europe/Zurich"
