# OpenRemote v3
#
# Profile that runs the vanilla stack on https://localhost using a self-signed SSL certificate,
# with username 'admin' and password 'secret'. There is no map data available in the vanilla
# system so the map tile server will not function. Persistent data is stored in a docker
# volume called postgresql-data between restarts, simply delete this volume to reset the
# system to an empty state.
#
# Please see profile/deploy.yml for configuration details for each service.
#
version: "3.7"

networks:
  public:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true
  private:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true

volumes:
  proxy-data:
  postgresql-data:
  deployment-data:

x-app: &awslogs
  logging:
    driver: awslogs
    options:
      awslogs-region: ${AWS_REGION:-eu-west-1}
      awslogs-group:  ${AWSLOGS_GROUP:-openremote}
      awslogs-create-group: 'true'

services:
  proxy:
    image: openremote/proxy:${PROXY_VERSION:-2.1.2.4}
    networks:
      - public
      - private
    depends_on:
      - manager
    healthcheck:
      interval: 3s
      timeout: 3s
      start_period: 2s
      retries: 3
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:80"]
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - proxy-data:/deployment
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        window: 30s
      update_config:
        failure_action: rollback
        order: start-first
        delay: 30m
    environment:
      DOMAINNAME: ${DOMAINNAME:-localhost}
      LE_EMAIL: admin@${DOMAINNAME}
    <<: *awslogs

  manager:
    image: openremote/manager:${MANAGER_VERSION:-latest}
    networks:
      - private
    depends_on:
      - keycloak
    healthcheck:
      interval: 3s
      timeout: 3s
      start_period: 2s
      retries: 120
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080"]
    ports:
      # SNMP trap
      - "162:162/udp"
    volumes:
      - deployment-data:/deployment
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
        delay: 10s
    environment:
      SETUP_ADMIN_PASSWORD: ${PASSWORD:-secret}
      EXTERNAL_URL: ${EXTERNAL_URL:-https://localhost}
      SETUP_EMAIL_HOST: ${EMAIL_HOST:-email-smtp.eu-west-1.amazonaws.com}
      SETUP_EMAIL_USER: ${EMAIL_USER}
      SETUP_EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SETUP_EMAIL_PORT: ${SETUP_EMAIL_PORT:-587}
      SETUP_EMAIL_FROM_KEYCLOAK: no-reply@${DOMAINNAME}
      SETUP_EMAIL_FROM_DEFAULT: admin@${DOMAINNAME}
    <<: *awslogs

  keycloak:
    image: openremote/keycloak:${KEYCLOAK_VERSION:-13.0.1.3}
    networks:
      - public
      - private
    depends_on:
      - postgresql
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/auth"]
      interval: 3s
      timeout: 3s
      start_period: 60s
      retries: 30
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
        delay: 10m
    volumes:
      - deployment-data:/deployment
    environment:
      KEYCLOAK_PASSWORD: ${PASSWORD:-secret}
      KEYCLOAK_FRONTEND_URL: ${EXTERNAL_URL:-https://localhost}/auth
    <<: *awslogs

  postgresql:
    image: openremote/postgresql:${POSTGRESQL_VERSION:-9.6.21.0}
    networks:
      - private
    healthcheck:
      interval: 3s
      timeout: 3s
      start_period: 2s
      retries: 30
      test: ["CMD", "gosu", "postgres", "pg_isready"]
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
        delay: 20m
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    <<: *awslogs
