apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
  {{- if .Values.aws.enabled }}
  labels:
    type: amazonEBS
  {{- end }}

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  {{- if .Values.aws.enabled }}
  awsElasticBlockStore:
    volumeID: {{ .Values.aws.psqlVolumeId }}
    fsType: ext4
  {{- else }}
  hostPath:
    path: "{{ .Values.basePath}}/postgresql-data"
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
