# ---------------------------------------------------------------------------------------------------------------------
# This workflow handles creation of AWS member accounts by calling (.ci_cd/aws/provision_account.sh)
# You need to be a member of the CI/CD github team to use this action as it will incur costs for the organisation.
# ---------------------------------------------------------------------------------------------------------------------

name: Provision Account

on:
  workflow_dispatch:
    inputs:
      ACCOUNT_NAME:
        description: 'New account name (lowercase simple values recommended)'
        required: false
        type: string
      PARENT_DNS_ZONE:
        description: 'Name of parent hosted domain zone in management account'
        type: string
        default: openremote.app
        required: true
      VPC_PEER:
        description: 'Create VPC peering connection with management account'
        type: boolean
        default: true
        required: false
      HOSTED_DNS:
        description: 'Create hosted domain zone in new account'
        type: boolean
        required: false
      OU:
        description: 'Organisational unit to use for account'
        type: string
        default: Custom

jobs:

  provision:
    name: Provision
    runs-on: ubuntu-latest

    steps:

      - name: Check CI/CD team membership
        uses: tspascoal/get-user-teams-membership@v2
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          organization: openremote
          team: CI/CD
          GITHUB_TOKEN: ${{ secrets._TEMP_ACCESS_TOKEN_FOR_READING_ORG_TEAMS }} # Personal access token used to query github (Requires scope: `read:org`)

      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision Account
        if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        run: |
          chmod +x .ci_cd/aws/*
          .ci_cd/aws/provision_account.sh "$OU" "$ACCOUNT_NAME" "$PARENT_DNS_ZONE" "$HOSTED_DNS" "$VPC_PEER"
        env:
          OU: ${{ github.event.inputs.OU }}
          ACCOUNT_NAME: ${{ github.event.inputs.ACCOUNT_NAME }}
          PARENT_DNS_ZONE: ${{ github.event.inputs.PARENT_DNS_ZONE }}
          HOSTED_DNS: ${{ github.event.inputs.HOSTED_DNS }}
          VPC_PEER: ${{ github.event.inputs.VPC_PEER }}
          AWS_ACCESS_KEY_ID: ${{ secrets._TEMP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets._TEMP_AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_NAME: ${{ secrets._TEMP_AWS_ROLE_NAME }}
