apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../kube-docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: manager
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../kube-docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: manager
    spec:
      containers:
      - env:
        - name: IDENTITY_NETWORK_HOST
          value: localhost
        - name: IDENTITY_NETWORK_SECURE
          value: "true"
        - name: IDENTITY_NETWORK_WEBSERVER_PORT
          value: "443"
        - name: JAVA_OPTS
          value: -Xms400m -Xmx400m -XX:CompressedClassSpaceSize=25m -XX:MaxMetaspaceSize=150m
            -XX:InitialCodeCacheSize=50m -XX:ReservedCodeCacheSize=50m -XX:MaxDirectMemorySize=25m
            -XX:NativeMemoryTracking=summary -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/javadump.core.hprof
        - name: KEYCLOAK_HOST
          value: keycloak
        - name: KEYCLOAK_PORT
          value: "8080"
        - name: SETUP_ADMIN_PASSWORD
          value: secret
        - name: SETUP_WIPE_CLEAN_INSTALL
          value: "true"
        - name: TZ
          value: Europe/Amsterdam
        image: openremote/manager-swarm:latest
        imagePullPolicy: ""
        name: manager
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
